name: "webApp"
mode: "dev"
port: 8080
version: "v0.0.1"
log_type: "console"
log:
  level: "debug"
  filename: "webApp.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "testDB"
  max_open_conn: 20
  max_idle_conn: 20
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100